config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # 
  resources :access_records
  post 'get_project_by_client' => 'access_records#get_project_by_client'
end

app/models/access_record.rb
class AccessRecord < ApplicationRecord
  enum access_type: [:FTP, :SQL, :SSH, :SFTP, :URL, :RDP, :SMTP, :TCP, :UDP, :SMB, :NFS, :LDAP  ]

  ACCESS_TYPE = { 'FTP' => 'FTP', 'SQL' => 'SQL', 'SSH' => 'SSH', 'SFTP' => 'SFTP', 'URL' => 'URL', 'RDP' => 'RDP', 'SMTP' => 'SMTP', 'TCP' => 'TCP', 'UDP' => 'UDP', 'SMB' => 'SMB', 'NFS' => 'NFS', 'LDAP' => 'LDAP'  }

  validates :client_id, :project_id ,:access_type ,presence: true 
  validates :host_address, presence: true
  validates :port, presence: true, numericality: { only_integer: true }
  validates :username, presence: true, length: { in: 2..100}
  validates :password, presence: true, length: { in: 2..100}

  belongs_to :client
  belongs_to :project

  scope :visible, ->(*args) do
    includes(:project)
      .references(:projects)
      .merge(Project.allowed_to(args.first || User.current, :view_access_records))
  end

  def self.latest_for(user, count: 20)
    scope = newest_first
            .visible(user)

    if count > 0
      scope.limit(count)
    else
      scope
    end
  end

  # table_name shouldn't be needed :(
  def self.newest_first
    order "#{table_name}.id DESC"
  end

  def visible?(user = User.current)
    !user.nil? && user.allowed_to?(:view_news, project)
  end
end

app/controllers/access_records_controller.rb
class AccessRecordsController < ApplicationController
  include PaginationHelper
  layout :choose_layout
  include Concerns::Layout
  before_action :find_request_for_access
  before_action :find_access_record_object, except: %i[new create index]
  before_action :find_project_from_association, except: %i[new create index]
  before_action :find_project, only: %i[new create]
  before_action :authorize, except: [:index]
  before_action :find_optional_project, only: [:index]
  accept_key_auth :index
  before_action :require_admin

  def index
    if(check_path)
      scope = @project ? @project.access_records : AccessRecord.all
      @access_records = scope.merge(AccessRecord.latest_for(current_user, count: 0))
                    .page(page_param)
                    .per_page(per_page_param)

      respond_to do |format|
        format.html do
          render layout: layout_non_or_no_menu
        end
        format.atom do
          render_feed(@access_records,
                      title: (@project ? @project.name : Setting.app_title) + ": #{l(:label_client)}")
        end
      end
    else
      @access_records = ::AccessRecord.page(page_param).per_page(per_page_param) 
    end
  end

  current_menu_item :index do
    :access_records
  end

  def new
    @path = request.fullpath
    if(check_path)
      @access_record = AccessRecord.new(project: @project)
    else
      access_record = []
      @access_record = AccessRecord.new
      @projects = get_project(access_record)
      @clients = get_client
    end
  end 

  def edit
    @path = request.fullpath
    @access_record = AccessRecord.find(params[:id])
    @clients = get_client
    @projects = get_project(@access_record)
  end

  def create
    @access_record = AccessRecord.new(project: @project)
    @access_record.attributes = access_record_params
    if @access_record.save
      if(check_path)
        redirect_to access_records_path
      else
        redirect_to project_access_records_path
      end
    else
      render 'new'
    end
  end

  def update
    @access_record = AccessRecord.find(params[:id])
    
    if (@access_record.update(access_record_params))
      if(check_path)
        redirect_to access_records_path
      else
        redirect_to project_access_records_path
      end
    else
      render 'edit'
    end
  end

  def show
    @access_record = AccessRecord.find(params[:id])
  end

  def destroy
    @access_record = AccessRecord.find(params[:id])
    @access_record.destroy if @access_record
    unless check_path
      redirect_to access_records_path
    else
      redirect_to project_access_records_path
    end
  end

  def get_project_by_client
    client = Client.find(params[:id])
    @projects = client.projects
    respond_to do |format|
      format.json { render json: @projects }
    end

  end

  def show_local_breadcrumb
    true
  end

  def find_request_for_access
    check_path ? require_admin :  authorize
   end

  def choose_layout
    'admin' unless check_path    
    end
  end

  def find_project_from_association
    return true  unless check_path
    render_404 unless @object.present?
    @project = @object.project
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_access_record_object
    return true unless check_path
    @news = @object = AccessRecord.find(params[:id].to_i)
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_optional_project
    return true unless params[:project_id]
    @project = Project.find(params[:project_id])
    authorize
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_project
    return true unless check_path)
    @project = Project.find(params[:project_id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end


  def check_path
    @path = request.fullpath
    return @path.include? ('project') ? true : false 
  end
  
  private
    def access_record_params
      params.require(:access_record).permit(:client_id, :project_id, :access_type, :host_address, :port, :username, :password, :description )    
    end

  def get_client
    Client.all
  end

  def get_project(access_record)
    access_record.blank? ? Project.all :  Project.where("client_id = ?", access_record.client_id)
  end

end

app/helpers/access_records_helper.rb
module AccessRecordsHelper
end

app/views/access_records/_admin_form.html.erb
<%= form_with(model: @access_record, local: true) do |f| %>

  <% if @access_record.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@access_record.errors.count, "error") %>
        this access_record from being saved:
      </h2>
      <ul>
        <% @access_record.errors.full_messages.each do |msg| %>
          <li><%= msg  %></li>
        <% end %> 
      </ul>
    </div>
  <% end %>

  <section class="form--section">
    <div class="form--field -required">
      <%= styled_label_tag "Client Name", "Client Name" %>
      <div class="form--field-container">
        <span class="form--field-container">
          <span class="form--text-field-container -middle">
            <%= f.select(:client_id, options_for_select(
        @clients.collect{ |c| [c.company_name, c.id] }, :selected => f.object.client_id),class: 'new', include_blank: "Select a Client") %>
          </span>
        </span>
      </div>
    </div>
    <div class="form--field -required">
      <%= styled_label_tag "Project Namme", "Project Name" %>
      <div class="form--field-container">
        <span class="form--field-container">
          <span class="form--text-field-container -middle">
            <%= f.select(:project_id, options_for_select(
        @projects.collect{ |p| [p.name, p.id] }, :selected => f.object.project_id), container_class: '-middle', include_blank: "Select a Project") %>
          </span>
        </span>
      </div>
    </div>
    <div class="form--field -required">
      <label class="form--label" title="Access Type" for="access_record_access_type">Access Type</label>
      <span class="form--field-container">
        <span class="form--text-field-container -middle">
          <%= f.select(:access_type, AccessRecord::ACCESS_TYPE.collect {|k, v| [ k, v ] }, {:selected => f.object.access_type, include_blank: "Select a Access Type", :class => 'new', :id => 'new', required: true }) %>
        </span>
      </span>
    </div>
    <div class="form--field -required">
      <label class="form--label" title="Host Address" for="access_record_host_address">Host Address</label>
      <span class="form--field-container">
        <span class="form--text-field-container -middle">
          <%= f.text_field :host_address, container_class: '-middle',  required: true %>
        </span>
      </span>
    </div>
    <div class="form--field -required">
      <label class="form--label" title="Port" for="access_record_port">Port</label>
      <span class="form--field-container">
        <span class="form--text-field-container -middle">
          
          <%= f.text_field :port, autofocus: true, container_class: '-middle',  required: true %>
        </span>
      </span>
    </div>
    <div class="form--field -required">
      <label class="form--label" title="Username" for="access_record_username">Username</label>
      <span class="form--field-container">
        <span class="form--text-field-container -middle">
          <%= f.text_field :username, autofocus: true, container_class: '-middle',  required: true%>
        </span>
      </span>
    </div>
    <div class="form--field -required">
      <label class="form--label" title="Password" for="access_record_password">Password</label>
      <span class="form--field-container">
        <span class="form--text-field-container -middle" id="password" style="max-width: 340px !important;">
          <%= f.password_field(:password, value: @access_record.password, required: true) %>
        </span>
        <span class="form--field-affix icon-action-menu icon-unwatched" id="showPassword"></span>
      </span>
    </div>
    <div class="form--field">
      <label class="form--label" title="Description" for="access_record_description">Description</label>
      <span class="form--field-container">
        <span class="form--text-field-container -middle">
          <%= f.text_area :description, container_class: '-middle' %>
        </span>
      </span>
    </div>
  </section>

  <p>
    <%= styled_button_tag "Submit", class: '-highlight -with-icon icon-checkmark' %>
  </p>

<% end %>

app/views/access_records/_form.html.erb
<%= form_with(model: [@project, @access_record], local: true) do |f| %>

  <% if @access_record.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@access_record.errors.count, "error") %>
        this access_record from being saved:
      </h2>
      <ul>
        <% @access_record.errors.full_messages.each do |msg| %>
          <li><%= msg  %></li>
        <% end %> 
      </ul>
    </div>
  <% end %>

  <section class="form--section">
    <div class="form--field -required">
      <label class="form--label" title="Client" for="access_record_client">Client</label>
      <span class="form--field-container">
        <span class="form--text-field-container -middle">
          <%= f.text_field :client, value: @project.client.company_name, readonly: true,  required: true %>
          <%= f.hidden_field :client_id, value: @project.client_id, required: true %>
        </span>
      </span>
    </div>

    <div class="form--field -required">
      <label class="form--label" title="Project" for="access_record_project">Project</label>
      <span class="form--field-container">
        <span class="form--text-field-container -middle">
          <%= f.text_field :project, value: @project.name, readonly: true,  required: true %>
          <%= f.hidden_field :project_id, value: @project.id, required: true %>
        </span>
      </span>
    </div>

    <div class="form--field -required">
      <label class="form--label" title="Access Type" for="access_record_access_type">Access Type</label>
      <span class="form--field-container">
        <span class="form--text-field-container -middle">
          <%= f.select(:access_type, AccessRecord::ACCESS_TYPE.collect {|k, v| [ k, v ] }, {:selected => f.object.access_type, include_blank: "Select a Access Type", :class => 'new', :id => 'new', required: true }) %>
        </span>
      </span>
    </div>

    <div class="form--field -required">
      <label class="form--label" title="Host Address" for="access_record_host_address">Host Address</label>
      <span class="form--field-container">
        <span class="form--text-field-container -middle">
          <%= f.text_field :host_address, container_class: '-middle',  required: true %>
        </span>
      </span>
    </div>

    <div class="form--field -required">
      <label class="form--label" title="Port" for="access_record_port">Port</label>
      <span class="form--field-container">
        <span class="form--text-field-container -middle">
          
          <%= f.text_field :port, autofocus: true, container_class: '-middle',  required: true %>
        </span>
      </span>
    </div>

    <div class="form--field -required">
      <label class="form--label" title="Username" for="access_record_username">Username</label>
      <span class="form--field-container">
        <span class="form--text-field-container -middle">
          <%= f.text_field :username, autofocus: true, container_class: '-middle',  required: true%>
        </span>
      </span>
    </div>

    <div class="form--field -required">
      <label class="form--label" title="Password" for="access_record_password">Password</label>
      <span class="form--field-container">
        <span class="form--text-field-container -middle" id="password" style="max-width: 340px !important;">
          <%= f.password_field(:password, value: @access_record.password, required: true) %>
        </span>
        <span class="form--field-affix icon-action-menu icon-unwatched" id="showPassword"></span>
      </span>
    </div>
    
    <div class="form--field">
      <label class="form--label" title="Description" for="access_record_description">Description</label>
      <span class="form--field-container">
        <span class="form--text-field-container -middle">
          <%= f.text_area :description, container_class: '-middle' %>
        </span>
      </span>
    </div>
  </section>

  <p>
    <%= styled_button_tag "Submit", class: '-highlight -with-icon icon-checkmark' %>
  </p>

<% end %>

app/views/access_records/_link.html.erb
<% if (!@path.include? ('project')) %>
  <%= link_to('', edit_access_record_path(@acc_record),class: 'icon icon-edit',
      title: "Edit" )%>&nbsp; &nbsp;
  <%= link_to('', access_record_path(@acc_record), method: :get,
      class: 'icon-action-menu icon-watched',
      title: "Show",
      :data => { :toggle => 'modal', :target => '#myModal'  }
      ) 
       %>&nbsp;

  <%= link_to('', access_record_path(@acc_record), method: :delete, 
      data: {confirm: "Are you sure want to delete?"},
      class: 'icon icon-delete',
      title: "Delete")
       %>
  
<% else %>
  <% if @edit_access_record %>
    <%= link_to('', edit_project_access_record_path(@project, @acc_record),class: 'icon icon-edit',
      title: "Edit" )%>&nbsp; &nbsp;
  <% end %>
  <% if @view_access_record %>
    <%= link_to('', project_access_record_path(@project,@acc_record), method: :get,
      class: 'icon-action-menu icon-watched',
      title: "Show",
      :data => { :toggle => 'modal', :target => '#myModal'  }
      ) 
       %>&nbsp;
  <% end %>
  <% if @delete_access_record %>
    <%= link_to('', project_access_record_path(@project,@acc_record), method: :delete, 
      data: {confirm: "Are you sure want to delete?"},
      class: 'icon icon-delete',
      title: "Delete")
       %>
  <% end %>
<% end %>

app/views/access_records/edit.html.erb
<% html_title l(:label_administration), "Edit Access Record" %>
<% local_assigns[:additional_breadcrumb] = t(:label_access_record_edit) %>
<%= breadcrumb_toolbar t(:label_access_record_edit) %>
<%= javascript_include_tag 'access_record.js'%>

<% if (!@path.include? ('project')) %>
  <%= render 'admin_form' %>
<% else %>
  <%= render 'form' %>
<% end %>

app/views/access_records/index.html.erb
<%
  @list_access_record = User.current.allowed_to?(:list_access_record, @project)
  @view_access_record = User.current.allowed_to?(:view_access_record, @project)
  @add_access_record = User.current.allowed_to?(:add_access_record, @project)
  @edit_access_record = User.current.allowed_to?(:edit_access_record, @project)
  @delete_access_record = User.current.allowed_to?(:delete_access_record, @project)
 %>
  
  <% html_title l(:label_administration), "Access Records" %>

  <%= toolbar title: "Access Records" do %>
    <% if (!@path.include? ('project')) %>
      <li class="toolbar-item">
        <%= link_to new_access_record_path(@project),
              { class: 'button -alt-highlight',
                aria: {label: "Access Record"},
                title: "Access Records"} do %>
          <%= op_icon('button--icon icon-add') %>
          <span class="button--text"><%= "Access Record" %></span>
        <% end %>
      </li>
    <% elsif @add_access_record %>
      <li class="toolbar-item">
        <%= link_to new_project_access_record_path(@project),
              { class: 'button -alt-highlight',
                aria: {label: "Access Record"},
                title: "Access Records"} do %>
          <%= op_icon('button--icon icon-add') %>
          <span class="button--text"><%= "Access Record" %></span>
        <% end %>
      </li>
    <% end %>
  <% end %>
  <% if @access_records.any? %>
    <div class="generic-table--container">
      <div class="generic-table--results-container">
        <table class="generic-table">
          <colgroup>
            <col highlight-col>
            <col highlight-col>
            <col highlight-col>
            <col highlight-col>
            <col highlight-col>
            <col>
          </colgroup>
          <thead>
            <tr>
                <th>Client Name</th>
                <th>Project Name</th>
                <th>Access Type</th>
                <th>Host Address</th>
                <% if (@edit_access_record || @view_access_record ||  @delete_access_record) || (!@path.include? ('project'))  %>
                <th>Actions</th>
                <% end %>
            </tr>
          </thead>
          <tbody>
            <% @access_records.each do |access_record|  %>
              <% @acc_record = access_record %>
              <tr class="user">
                <td class="company_name"><%= @acc_record.client.company_name %></td>
                <td class="project_name"><%= @acc_record.project.name %></td>
                <td class="access_type"><%= @acc_record.access_type %></td>
                <td class="host_address"><%= @acc_record.host_address %></td>
                <% if (@edit_access_record || @view_access_record ||  @delete_access_record) || (!@path.include? ('project')) %>
                  <td class="">
                    <%= render 'link' %>
                  </td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <%= pagination_links_full @access_records %>
  <% else %>
    <%= no_results_box(action_url: new_access_record_path, display_action: true)%>
  <% end %>

app/views/access_records/new.html.erb
<% html_title l(:label_administration), "New Access Record" %>
<% local_assigns[:additional_breadcrumb] = t(:label_access_record_new) %>
<%= breadcrumb_toolbar t(:label_access_record_new) %>
<%= javascript_include_tag 'access_record.js'%>

<% if (!@path.include? ('project')) %>
  <%= render 'admin_form' %>
<% else %>
  <%= render 'form' %>
<% end %>

app/views/access_records/show.html.erb
<% html_title l(:label_administration), "Show Access Record" %>
<% local_assigns[:additional_breadcrumb] = t(:label_access_record_show) %>
<%= breadcrumb_toolbar t(:label_access_record_show) %>
  <section class="form--section">
    <div class="form--field">
      <label class="form--label" for="company_name">
        <strong>Company Name :</strong>
      </label>
      <div class="form--field-container">
        <%= @access_record.client.company_name %>
      </div>
    </div>
    <div class="form--field">
      <label class="form--label" for="project_name">
        <strong>Project Name :</strong>
      </label>
      <div class="form--field-container">
        <%= @access_record.project.name %>
      </div>
    </div>
    <div class="form--field">
      <label class="form--label" for="access_type">
        <strong>Access Type :</strong>
      </label>
      <div class="form--field-container">
        <%= @access_record.access_type %>
      </div>
    </div>
    <div class="form--field">
      <label class="form--label" for="host_address">
        <strong>Host Address :</strong>
      </label>
      <div class="form--field-container">
        <%= @access_record.host_address %>
      </div>
    </div>
    <div class="form--field">
      <label class="form--label" for="port">
        <strong>Port :</strong>
      </label>
      <div class="form--field-container">
        <%= @access_record.port %>
      </div>
    </div>
    <div class="form--field">
      <label class="form--label" for="username">
        <strong>User Name :</strong>
      </label>
      <div class="form--field-container">
        <%= @access_record.username %>
      </div>
    </div>
    <div class="form--field">
      <label class="form--label" for="password">
        <strong>Password :</strong>
      </label>
      <div class="form--field-container">
        <%= @access_record.password %>
      </div>
    </div>
    <div class="form--field">
      <label class="form--label" for="description">
        <strong>Description :</strong>
      </label>
      <div class="form--field-container">
        <%= @access_record.description %>
      </div>
    </div>
  </section>